"""
Tetris - a simple, easy-to-play block puzzle game.

Controls:
    Left / Right Arrow  - move piece
    Down Arrow          - soft drop (move down faster)
    Up Arrow             - rotate piece
    Space                - hard drop (instantly drop piece)
    P                    - pause / unpause
    R                    - restart after game over
    Esc                  - quit

Levels go from 0 to 9. You start at level 0 (slowest) and level up
every time you clear 10 lines. Each level makes the blocks fall faster.
"""

import pygame
import random

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

COLS = 10
ROWS = 20
CELL_SIZE = 30

SIDE_PANEL_WIDTH = 200
BOARD_WIDTH = COLS * CELL_SIZE
BOARD_HEIGHT = ROWS * CELL_SIZE
SCREEN_WIDTH = BOARD_WIDTH + SIDE_PANEL_WIDTH
SCREEN_HEIGHT = BOARD_HEIGHT

MAX_LEVEL = 9
LINES_PER_LEVEL = 10

# Fall speed (milliseconds between automatic drops) for each level 0-9.
# Level 0 is slow and easy; level 9 is fast.
LEVEL_SPEEDS_MS = [800, 720, 630, 550, 470, 390, 310, 230, 160, 100]

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GRAY = (40, 40, 40)
LIGHT_GRAY = (90, 90, 90)

def _rotate_grid_cw(grid):
    """Rotate a square grid of strings 90 degrees clockwise.

    Rotating around a proper matrix center (rather than hand-picking each
    rotation state by eye) guarantees the shape always turns around the same
    fixed point, instead of drifting depending on which state it's in.
    """
    n = len(grid)
    new_rows = [[" "] * n for _ in range(n)]
    for r in range(n):
        for c, ch in enumerate(grid[r]):
            new_rows[c][n - 1 - r] = ch
    return ["".join(row) for row in new_rows]


def _build_rotations(base_grid, count=4):
    rotations = [base_grid]
    current = base_grid
    for _ in range(count - 1):
        current = _rotate_grid_cw(current)
        rotations.append(current)
    return rotations


# Tetromino shapes. I and O are hand-picked (they're symmetric enough that
# a couple of fixed states look best). T, S, Z, J and L are generated by
# rotating a single 3x3 base shape, so every rotation turns around the same
# true center cell instead of jumping between inconsistent hand-drawn states.
SHAPES = {
    "I": [
        ["....",
         "XXXX",
         "....",
         "...."],
        ["..X.",
         "..X.",
         "..X.",
         "..X."],
    ],
    "O": [
        ["....",
         ".XX.",
         ".XX.",
         "...."],
    ],
    "T": _build_rotations([".X.",
                            "XXX",
                            "..."]),
    "S": _build_rotations([".XX",
                            "XX.",
                            "..."]),
    "Z": _build_rotations(["XX.",
                            ".XX",
                            "..."]),
    "J": _build_rotations(["X..",
                            "XXX",
                            "..."]),
    "L": _build_rotations(["..X",
                            "XXX",
                            "..."]),
}

SHAPE_COLORS = {
    "I": (0, 240, 240),
    "O": (240, 240, 0),
    "T": (160, 0, 240),
    "S": (0, 240, 0),
    "Z": (240, 0, 0),
    "J": (0, 0, 240),
    "L": (240, 160, 0),
}


class Piece:
    def __init__(self, kind):
        self.kind = kind
        self.rotation = 0
        self.rotations = SHAPES[kind]
        self.color = SHAPE_COLORS[kind]
        # Spawn roughly centered at the top of the board.
        self.col = COLS // 2 - 2
        self.row = -1

    def cells(self, rotation=None, row=None, col=None):
        """Return the list of (row, col) board cells this piece occupies."""
        rotation = self.rotation if rotation is None else rotation
        row = self.row if row is None else row
        col = self.col if col is None else col
        grid = self.rotations[rotation % len(self.rotations)]
        result = []
        for r, line in enumerate(grid):
            for c, ch in enumerate(line):
                if ch == "X":
                    result.append((row + r, col + c))
        return result


class Tetris:
    def __init__(self):
        self.board = [[None for _ in range(COLS)] for _ in range(ROWS)]
        self.score = 0
        self.lines_cleared_total = 0
        self.level = 0
        self.game_over = False
        self.paused = False
        self.bag = []
        self.current = self._spawn_piece()
        self.next_kind = self._next_from_bag()
        self.fall_timer = 0.0
        self.flash_rows = []
        self.flash_timer = 0

    # -- Piece generation ---------------------------------------------------

    def _next_from_bag(self):
        """7-bag randomizer: each of the 7 pieces appears once per bag."""
        if not self.bag:
            self.bag = list(SHAPES.keys())
            random.shuffle(self.bag)
        return self.bag.pop()

    def _spawn_piece(self):
        kind = getattr(self, "next_kind", None) or self._next_from_bag()
        self.next_kind = self._next_from_bag()
        piece = Piece(kind)
        if self._collides(piece, piece.row, piece.col, piece.rotation):
            self.game_over = True
        return piece

    # -- Collision & board helpers -------------------------------------------

    def _collides(self, piece, row, col, rotation):
        for r, c in piece.cells(rotation, row, col):
            if c < 0 or c >= COLS or r >= ROWS:
                return True
            if r >= 0 and self.board[r][c] is not None:
                return True
        return False

    def _lock_piece(self):
        for r, c in self.current.cells():
            if r < 0:
                self.game_over = True
                continue
            self.board[r][c] = self.current.color
        self._check_lines()
        self.current = self._spawn_piece()

    def _check_lines(self):
        full_rows = [r for r in range(ROWS) if all(self.board[r][c] is not None for c in range(COLS))]
        if not full_rows:
            return
        for r in full_rows:
            del self.board[r]
            self.board.insert(0, [None for _ in range(COLS)])

        cleared = len(full_rows)
        self.lines_cleared_total += cleared
        # Classic-ish scoring, scaled a bit by level.
        line_scores = {1: 40, 2: 100, 3: 300, 4: 1200}
        self.score += line_scores.get(cleared, 0) * (self.level + 1)

        new_level = min(MAX_LEVEL, self.lines_cleared_total // LINES_PER_LEVEL)
        self.level = new_level

    # -- Player actions -------------------------------------------------------

    def move(self, dcol):
        if self.game_over or self.paused:
            return
        piece = self.current
        if not self._collides(piece, piece.row, piece.col + dcol, piece.rotation):
            piece.col += dcol

    def rotate(self):
        if self.game_over or self.paused:
            return
        piece = self.current
        new_rotation = (piece.rotation + 1) % len(piece.rotations)
        # Simple wall/floor kick: try the natural spot, then nearby offsets.
        # The row offsets matter because some rotation states of a piece
        # (e.g. the T-piece lying flat) are shorter than others, so rotating
        # into a taller state while resting on the floor or a stack needs a
        # bit of extra headroom, not just sideways room.
        for drow, dcol in ((0, 0), (0, -1), (0, 1), (0, -2), (0, 2),
                            (-1, 0), (-1, -1), (-1, 1)):
            if not self._collides(piece, piece.row + drow, piece.col + dcol, new_rotation):
                piece.row += drow
                piece.col += dcol
                piece.rotation = new_rotation
                return

    def soft_drop(self):
        if self.game_over or self.paused:
            return
        self._step_down(scored=True)

    def hard_drop(self):
        if self.game_over or self.paused:
            return
        piece = self.current
        distance = 0
        while not self._collides(piece, piece.row + 1, piece.col, piece.rotation):
            piece.row += 1
            distance += 1
        self.score += distance * 2
        self._lock_piece()

    def _step_down(self, scored=False):
        piece = self.current
        if not self._collides(piece, piece.row + 1, piece.col, piece.rotation):
            piece.row += 1
            if scored:
                self.score += 1
        else:
            self._lock_piece()

    def update(self, dt_ms):
        if self.game_over or self.paused:
            return
        self.fall_timer += dt_ms
        speed = LEVEL_SPEEDS_MS[self.level]
        if self.fall_timer >= speed:
            self.fall_timer = 0
            self._step_down()

    def ghost_row(self):
        """Row where the current piece would land if hard-dropped now."""
        piece = self.current
        row = piece.row
        while not self._collides(piece, row + 1, piece.col, piece.rotation):
            row += 1
        return row

    def reset(self):
        self.__init__()


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def draw_cell(surface, row, col, color, ghost=False):
    x = col * CELL_SIZE
    y = row * CELL_SIZE
    rect = pygame.Rect(x, y, CELL_SIZE, CELL_SIZE)
    if ghost:
        pygame.draw.rect(surface, color, rect, width=2)
    else:
        pygame.draw.rect(surface, color, rect)
        pygame.draw.rect(surface, BLACK, rect, width=1)


def draw_board(surface, game):
    surface.fill(BLACK, pygame.Rect(0, 0, BOARD_WIDTH, BOARD_HEIGHT))

    # Grid lines.
    for c in range(COLS + 1):
        x = c * CELL_SIZE
        pygame.draw.line(surface, GRAY, (x, 0), (x, BOARD_HEIGHT))
    for r in range(ROWS + 1):
        y = r * CELL_SIZE
        pygame.draw.line(surface, GRAY, (0, y), (BOARD_WIDTH, y))

    # Locked blocks.
    for r in range(ROWS):
        for c in range(COLS):
            color = game.board[r][c]
            if color is not None:
                draw_cell(surface, r, c, color)

    if not game.game_over:
        # Ghost piece (preview of where it will land).
        ghost_row = game.ghost_row()
        piece = game.current
        for r, c in piece.cells(row=ghost_row):
            if r >= 0:
                draw_cell(surface, r, c, piece.color, ghost=True)

        # Current piece.
        for r, c in piece.cells():
            if r >= 0:
                draw_cell(surface, r, c, piece.color)


def draw_mini_piece(surface, kind, top_left, cell=20):
    grid = SHAPES[kind][0]
    color = SHAPE_COLORS[kind]
    ox, oy = top_left
    for r, line in enumerate(grid):
        for c, ch in enumerate(line):
            if ch == "X":
                rect = pygame.Rect(ox + c * cell, oy + r * cell, cell, cell)
                pygame.draw.rect(surface, color, rect)
                pygame.draw.rect(surface, BLACK, rect, width=1)


def draw_side_panel(surface, font, big_font, game):
    panel_rect = pygame.Rect(BOARD_WIDTH, 0, SIDE_PANEL_WIDTH, SCREEN_HEIGHT)
    surface.fill((20, 20, 20), panel_rect)

    x = BOARD_WIDTH + 20
    y = 20

    def label(text, yy, font_obj=font, color=WHITE):
        img = font_obj.render(text, True, color)
        surface.blit(img, (x, yy))

    label("SCORE", y)
    label(str(game.score), y + 25, font_obj=big_font)
    y += 70

    label("LEVEL", y)
    label(f"{game.level} / {MAX_LEVEL}", y + 25, font_obj=big_font)
    y += 70

    label("LINES", y)
    label(str(game.lines_cleared_total), y + 25, font_obj=big_font)
    y += 70

    label("NEXT", y)
    draw_mini_piece(surface, game.next_kind, (x, y + 25))
    y += 120

    label("Left/Right: move", y, font_obj=font, color=LIGHT_GRAY)
    label("Up: rotate", y + 18, font_obj=font, color=LIGHT_GRAY)
    label("Down: soft drop", y + 36, font_obj=font, color=LIGHT_GRAY)
    label("Space: hard drop", y + 54, font_obj=font, color=LIGHT_GRAY)
    label("P: pause", y + 72, font_obj=font, color=LIGHT_GRAY)

    if game.paused and not game.game_over:
        label("PAUSED", y + 110, font_obj=big_font, color=(255, 220, 0))

    if game.game_over:
        label("GAME OVER", y + 100, font_obj=big_font, color=(255, 60, 60))
        label("Press R", y + 130, font_obj=font, color=WHITE)
        label("to restart", y + 148, font_obj=font, color=WHITE)


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def main():
    pygame.init()
    pygame.display.set_caption("Tetris")
    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    clock = pygame.time.Clock()

    font = pygame.font.SysFont("Arial", 18)
    big_font = pygame.font.SysFont("Arial", 28, bold=True)

    board_surface = pygame.Surface((BOARD_WIDTH, BOARD_HEIGHT))

    game = Tetris()

    # Key repeat for smooth held-key movement.
    pygame.key.set_repeat(180, 60)

    running = True
    while running:
        dt_ms = clock.tick(60)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_r and game.game_over:
                    game.reset()
                elif event.key == pygame.K_p and not game.game_over:
                    game.paused = not game.paused
                elif not game.game_over and not game.paused:
                    if event.key == pygame.K_LEFT:
                        game.move(-1)
                    elif event.key == pygame.K_RIGHT:
                        game.move(1)
                    elif event.key == pygame.K_DOWN:
                        game.soft_drop()
                    elif event.key == pygame.K_UP:
                        game.rotate()
                    elif event.key == pygame.K_SPACE:
                        game.hard_drop()

        game.update(dt_ms)

        draw_board(board_surface, game)
        screen.blit(board_surface, (0, 0))
        draw_side_panel(screen, font, big_font, game)

        pygame.display.flip()

    pygame.quit()


if __name__ == "__main__":
    main()
