/*
Tetris - a simple, easy-to-play block puzzle game.

Controls:
    Left / Right Arrow  - move piece
    Down Arrow          - soft drop (move down faster)
    Up Arrow            - rotate piece
    Space               - hard drop (instantly drop piece)
    P                   - pause / unpause
    R                   - restart after game over

Levels go from 0 to 9. You start at level 0 (slowest) and level up
every time you clear 10 lines. Each level makes the blocks fall faster.
*/

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const COLS = 10;
const ROWS = 20;
const CELL_SIZE = 30;

const SIDE_PANEL_WIDTH = 200;
const BOARD_WIDTH = COLS * CELL_SIZE;
const BOARD_HEIGHT = ROWS * CELL_SIZE;

const MAX_LEVEL = 9;
const LINES_PER_LEVEL = 10;

// Fall speed (milliseconds between automatic drops) for each level 0-9.
// Level 0 is slow and easy; level 9 is fast.
const LEVEL_SPEEDS_MS = [800, 720, 630, 550, 470, 390, 310, 230, 160, 100];

const BLACK = "#000000";
const WHITE = "#ffffff";
const GRAY = "#282828";
const LIGHT_GRAY = "#5a5a5a";

function rotateGridCW(grid) {
    // Rotate a square grid of strings 90 degrees clockwise.
    //
    // Rotating around a proper matrix center (rather than hand-picking each
    // rotation state by eye) guarantees the shape always turns around the
    // same fixed point, instead of drifting depending on which state it's in.
    const n = grid.length;
    const newRows = Array.from({ length: n }, () => new Array(n).fill(" "));
    for (let r = 0; r < n; r++) {
        for (let c = 0; c < grid[r].length; c++) {
            newRows[c][n - 1 - r] = grid[r][c];
        }
    }
    return newRows.map((row) => row.join(""));
}

function buildRotations(baseGrid, count = 4) {
    const rotations = [baseGrid];
    let current = baseGrid;
    for (let i = 0; i < count - 1; i++) {
        current = rotateGridCW(current);
        rotations.push(current);
    }
    return rotations;
}

// Tetromino shapes. I and O are hand-picked (they're symmetric enough that
// a couple of fixed states look best). T, S, Z, J and L are generated by
// rotating a single 3x3 base shape, so every rotation turns around the same
// true center cell instead of jumping between inconsistent hand-drawn states.
const SHAPES = {
    I: [
        ["....",
         "XXXX",
         "....",
         "...."],
        ["..X.",
         "..X.",
         "..X.",
         "..X."],
    ],
    O: [
        ["....",
         ".XX.",
         ".XX.",
         "...."],
    ],
    T: buildRotations([".X.",
                        "XXX",
                        "..."]),
    S: buildRotations([".XX",
                        "XX.",
                        "..."]),
    Z: buildRotations(["XX.",
                        ".XX",
                        "..."]),
    J: buildRotations(["X..",
                        "XXX",
                        "..."]),
    L: buildRotations(["..X",
                        "XXX",
                        "..."]),
};

const SHAPE_COLORS = {
    I: "rgb(0, 240, 240)",
    O: "rgb(240, 240, 0)",
    T: "rgb(160, 0, 240)",
    S: "rgb(0, 240, 0)",
    Z: "rgb(240, 0, 0)",
    J: "rgb(0, 0, 240)",
    L: "rgb(240, 160, 0)",
};

class Piece {
    constructor(kind) {
        this.kind = kind;
        this.rotation = 0;
        this.rotations = SHAPES[kind];
        this.color = SHAPE_COLORS[kind];
        // Spawn roughly centered at the top of the board.
        this.col = Math.floor(COLS / 2) - 2;
        this.row = -1;
    }

    // Return the list of [row, col] board cells this piece occupies.
    cells(rotation = this.rotation, row = this.row, col = this.col) {
        const grid = this.rotations[rotation % this.rotations.length];
        const result = [];
        for (let r = 0; r < grid.length; r++) {
            const line = grid[r];
            for (let c = 0; c < line.length; c++) {
                if (line[c] === "X") {
                    result.push([row + r, col + c]);
                }
            }
        }
        return result;
    }
}

class Tetris {
    constructor() {
        this.board = Array.from({ length: ROWS }, () => new Array(COLS).fill(null));
        this.score = 0;
        this.linesClearedTotal = 0;
        this.level = 0;
        this.gameOver = false;
        this.paused = false;
        this.bag = [];
        this.nextKind = this._nextFromBag();
        this.current = this._spawnPiece();
        this.fallTimer = 0;
    }

    // -- Piece generation ---------------------------------------------------

    _nextFromBag() {
        // 7-bag randomizer: each of the 7 pieces appears once per bag.
        if (this.bag.length === 0) {
            this.bag = Object.keys(SHAPES);
            for (let i = this.bag.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [this.bag[i], this.bag[j]] = [this.bag[j], this.bag[i]];
            }
        }
        return this.bag.pop();
    }

    _spawnPiece() {
        const kind = this.nextKind || this._nextFromBag();
        this.nextKind = this._nextFromBag();
        const piece = new Piece(kind);
        if (this._collides(piece, piece.row, piece.col, piece.rotation)) {
            this.gameOver = true;
        }
        return piece;
    }

    // -- Collision & board helpers -------------------------------------------

    _collides(piece, row, col, rotation) {
        for (const [r, c] of piece.cells(rotation, row, col)) {
            if (c < 0 || c >= COLS || r >= ROWS) {
                return true;
            }
            if (r >= 0 && this.board[r][c] !== null) {
                return true;
            }
        }
        return false;
    }

    _lockPiece() {
        for (const [r, c] of this.current.cells()) {
            if (r < 0) {
                this.gameOver = true;
                continue;
            }
            this.board[r][c] = this.current.color;
        }
        this._checkLines();
        this.current = this._spawnPiece();
    }

    _checkLines() {
        const fullRows = [];
        for (let r = 0; r < ROWS; r++) {
            if (this.board[r].every((cell) => cell !== null)) {
                fullRows.push(r);
            }
        }
        if (fullRows.length === 0) {
            return;
        }
        for (const r of fullRows) {
            this.board.splice(r, 1);
            this.board.unshift(new Array(COLS).fill(null));
        }

        const cleared = fullRows.length;
        this.linesClearedTotal += cleared;
        // Classic-ish scoring, scaled a bit by level.
        const lineScores = { 1: 40, 2: 100, 3: 300, 4: 1200 };
        this.score += (lineScores[cleared] || 0) * (this.level + 1);

        this.level = Math.min(MAX_LEVEL, Math.floor(this.linesClearedTotal / LINES_PER_LEVEL));
    }

    // -- Player actions -------------------------------------------------------

    move(dcol) {
        if (this.gameOver || this.paused) return;
        const piece = this.current;
        if (!this._collides(piece, piece.row, piece.col + dcol, piece.rotation)) {
            piece.col += dcol;
        }
    }

    rotate() {
        if (this.gameOver || this.paused) return;
        const piece = this.current;
        const newRotation = (piece.rotation + 1) % piece.rotations.length;
        // Simple wall/floor kick: try the natural spot, then nearby offsets.
        // The row offsets matter because some rotation states of a piece
        // (e.g. the T-piece lying flat) are shorter than others, so rotating
        // into a taller state while resting on the floor or a stack needs a
        // bit of extra headroom, not just sideways room.
        const kicks = [
            [0, 0], [0, -1], [0, 1], [0, -2], [0, 2],
            [-1, 0], [-1, -1], [-1, 1],
        ];
        for (const [drow, dcol] of kicks) {
            if (!this._collides(piece, piece.row + drow, piece.col + dcol, newRotation)) {
                piece.row += drow;
                piece.col += dcol;
                piece.rotation = newRotation;
                return;
            }
        }
    }

    softDrop() {
        if (this.gameOver || this.paused) return;
        this._stepDown(true);
    }

    hardDrop() {
        if (this.gameOver || this.paused) return;
        const piece = this.current;
        let distance = 0;
        while (!this._collides(piece, piece.row + 1, piece.col, piece.rotation)) {
            piece.row += 1;
            distance += 1;
        }
        this.score += distance * 2;
        this._lockPiece();
    }

    _stepDown(scored = false) {
        const piece = this.current;
        if (!this._collides(piece, piece.row + 1, piece.col, piece.rotation)) {
            piece.row += 1;
            if (scored) {
                this.score += 1;
            }
        } else {
            this._lockPiece();
        }
    }

    update(dtMs) {
        if (this.gameOver || this.paused) return;
        this.fallTimer += dtMs;
        const speed = LEVEL_SPEEDS_MS[this.level];
        if (this.fallTimer >= speed) {
            this.fallTimer = 0;
            this._stepDown();
        }
    }

    // Row where the current piece would land if hard-dropped now.
    ghostRow() {
        const piece = this.current;
        let row = piece.row;
        while (!this._collides(piece, row + 1, piece.col, piece.rotation)) {
            row += 1;
        }
        return row;
    }

    reset() {
        Object.assign(this, new Tetris());
    }
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function drawCell(ctx, row, col, color, ghost = false) {
    const x = col * CELL_SIZE;
    const y = row * CELL_SIZE;
    if (ghost) {
        ctx.strokeStyle = color;
        ctx.lineWidth = 2;
        ctx.strokeRect(x + 1, y + 1, CELL_SIZE - 2, CELL_SIZE - 2);
    } else {
        ctx.fillStyle = color;
        ctx.fillRect(x, y, CELL_SIZE, CELL_SIZE);
        ctx.strokeStyle = BLACK;
        ctx.lineWidth = 1;
        ctx.strokeRect(x + 0.5, y + 0.5, CELL_SIZE - 1, CELL_SIZE - 1);
    }
}

function drawBoard(ctx, game) {
    ctx.fillStyle = BLACK;
    ctx.fillRect(0, 0, BOARD_WIDTH, BOARD_HEIGHT);

    // Grid lines.
    ctx.strokeStyle = GRAY;
    ctx.lineWidth = 1;
    for (let c = 0; c <= COLS; c++) {
        const x = c * CELL_SIZE + 0.5;
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, BOARD_HEIGHT);
        ctx.stroke();
    }
    for (let r = 0; r <= ROWS; r++) {
        const y = r * CELL_SIZE + 0.5;
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(BOARD_WIDTH, y);
        ctx.stroke();
    }

    // Locked blocks.
    for (let r = 0; r < ROWS; r++) {
        for (let c = 0; c < COLS; c++) {
            const color = game.board[r][c];
            if (color !== null) {
                drawCell(ctx, r, c, color);
            }
        }
    }

    if (!game.gameOver) {
        // Ghost piece (preview of where it will land).
        const ghostRow = game.ghostRow();
        const piece = game.current;
        for (const [r, c] of piece.cells(undefined, ghostRow)) {
            if (r >= 0) {
                drawCell(ctx, r, c, piece.color, true);
            }
        }

        // Current piece.
        for (const [r, c] of piece.cells()) {
            if (r >= 0) {
                drawCell(ctx, r, c, piece.color);
            }
        }
    }
}

function drawMiniPiece(ctx, kind, ox, oy, cell = 20) {
    const grid = SHAPES[kind][0];
    const color = SHAPE_COLORS[kind];
    for (let r = 0; r < grid.length; r++) {
        const line = grid[r];
        for (let c = 0; c < line.length; c++) {
            if (line[c] === "X") {
                const x = ox + c * cell;
                const y = oy + r * cell;
                ctx.fillStyle = color;
                ctx.fillRect(x, y, cell, cell);
                ctx.strokeStyle = BLACK;
                ctx.lineWidth = 1;
                ctx.strokeRect(x + 0.5, y + 0.5, cell - 1, cell - 1);
            }
        }
    }
}

function drawSidePanel(ctx, game) {
    ctx.fillStyle = "rgb(20, 20, 20)";
    ctx.fillRect(BOARD_WIDTH, 0, SIDE_PANEL_WIDTH, BOARD_HEIGHT);

    const x = BOARD_WIDTH + 20;
    let y = 20;

    function label(text, yy, big = false, color = WHITE) {
        ctx.fillStyle = color;
        ctx.font = big ? "bold 22px Arial" : "14px Arial";
        ctx.textBaseline = "top";
        ctx.fillText(text, x, yy);
    }

    label("SCORE", y);
    label(String(game.score), y + 22, true);
    y += 70;

    label("LEVEL", y);
    label(`${game.level} / ${MAX_LEVEL}`, y + 22, true);
    y += 70;

    label("LINES", y);
    label(String(game.linesClearedTotal), y + 22, true);
    y += 70;

    label("NEXT", y);
    drawMiniPiece(ctx, game.nextKind, x, y + 25);
    y += 120;

    label("Left/Right: move", y, false, LIGHT_GRAY);
    label("Up: rotate", y + 18, false, LIGHT_GRAY);
    label("Down: soft drop", y + 36, false, LIGHT_GRAY);
    label("Space: hard drop", y + 54, false, LIGHT_GRAY);
    label("P: pause", y + 72, false, LIGHT_GRAY);

    if (game.paused && !game.gameOver) {
        label("PAUSED", y + 110, true, "rgb(255, 220, 0)");
    }

    if (game.gameOver) {
        label("GAME OVER", y + 100, true, "rgb(255, 60, 60)");
        label("Press R", y + 130);
        label("to restart", y + 148);
    }
}

// ---------------------------------------------------------------------------
// Main loop
// ---------------------------------------------------------------------------

function main() {
    const canvas = document.getElementById("game");
    const ctx = canvas.getContext("2d");

    const game = new Tetris();

    const keysNoRepeat = new Set(["ArrowUp", "Space", "KeyP", "KeyR"]);

    window.addEventListener("keydown", (event) => {
        if (keysNoRepeat.has(event.code) || event.code.startsWith("Arrow")) {
            event.preventDefault();
        }
        if (event.code === "KeyR" && game.gameOver) {
            game.reset();
            return;
        }
        if (event.code === "KeyP" && !game.gameOver) {
            if (!event.repeat) game.paused = !game.paused;
            return;
        }
        if (game.gameOver || game.paused) return;
        if (event.repeat && keysNoRepeat.has(event.code)) return;

        switch (event.code) {
            case "ArrowLeft":
                game.move(-1);
                break;
            case "ArrowRight":
                game.move(1);
                break;
            case "ArrowDown":
                game.softDrop();
                break;
            case "ArrowUp":
                game.rotate();
                break;
            case "Space":
                game.hardDrop();
                break;
        }
    });

    let lastTime = performance.now();

    function frame(now) {
        const dtMs = now - lastTime;
        lastTime = now;

        game.update(dtMs);

        drawBoard(ctx, game);
        drawSidePanel(ctx, game);

        requestAnimationFrame(frame);
    }

    requestAnimationFrame(frame);
}

main();
